name: Deploy to VPS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          port: ${{ secrets.VPS_PORT }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /var/www/bolaocopa/current
            git pull origin main
            npm ci
            npm run build
            systemctl restart bolaocopa
            nginx -t
            systemctl reload nginx
